### ISSUE TITLE
(sortof Offtopic): Timelapse video settings for Chrome and iPad?

### ISSUE THREAD

**Issue by koila91** [pageauc/pi-timolo#105]
(I know this has very little to do with pi-timolo - but maybe someone here has solved this.)

I use raspbian buster lite and ffmpeg for my daily timelapse conversion. Nothing I've found on ffmpeg forums or elsewhere has helped me to encode the videos so that I could watch them on an iPad - or in Chrome on Windows... at the moment only Microsoft Edge works. 

I'm not sure if this has something to do with the web server or the video file encoding. Does anyone have any ideas?

**Comment by pageauc** [comment]
Try re-encoding with handbrake.  It has Preset Button on Top Right Menu Bar and a list will appear on right pane..  The right hand pane has various selections for General, Web, Devices, Matorska and Production.  Lots of Choices.  You could try one of the Web or Devices options and see how you do.  I believe handbrake uses ffmpeg so if it works you might be able to find similar command line parameter selections that will solve your issue.

I use chrome for watching pi-timolo video's encoded with MP4Box without problem.  I just access though the pi-timolo web browser.

Claude ...
