### ISSUE TITLE
Image Rotation

### ISSUE THREAD

**Issue by dcrand2012** [pageauc/pi-timolo#13]
Hi Claude- This is what I have been looking for however the case and camera mounting I have requires the image to be rotated 270 degrees is there a way to do this?

**Comment by dcrand2012** [comment]
Nevermind when I made imageRotation Setting I spelled Rotation wrong Senior moments get you evry time. Thanks for a great application.

**Comment by pageauc** [comment]
I have commented out the camera rotation in the function takeDayImage(filename):
You can un comment the  camera.rotation line the comment out the vflip and hflip lines so the rotation is not overridden.  You will need to add a variable to config.py eg
cameraRotate = 270

   with picamera.PiCamera() as camera:
        camera.resolution = (imageWidth, imageHeight) 
        # camera.rotation = cameraRotate #Note use imageVFlip and imageHFlip variables
        time.sleep(0.5)   # sleep for a little while so camera can get adjustments
        if imagePreview:
            camera.start_preview()
        camera.vflip = imageVFlip
        camera.hflip = imageHFlip

Let me know if you have any issues.

**Comment by pageauc** [comment]
Also please note you will need to add similar logic to takeNightImage
Just add the line 
camera.rotation = cameraRotate

**Comment by dcrand2012** [comment]
Thanks for the fast reply It's working as I wanted.
