### ISSUE TITLE
Thread the camera image capture

### ISSUE THREAD

**Issue by MartinStolle** [pageauc/pi-timolo#27]

**Comment by pageauc** [comment]
Release 4.90 implements threaded video streaming for motion detection.  Still has to change to non thread mode to take quality full size images.   See config.py for new motionStreamOn variable.  This greatly improves speed of motion frames rate.  Also transitions are now pretty smooth with minimal or undetectable lighting changes.
minimal upgrade is (from logged in ssh or terminal session)

    cd ~/pi-timolo
    cp config.py config.py.old 
    wget -O config.py https://raw.github.com/pageauc/pi-timolo/master/source/config.py
    wget -O pi-timolo.py https://raw.github.com/pageauc/pi-timolo/master/source/pi-timolo.py

It is recommended that you have the latest raspbian firmware. Older firmware may work but I have not tested this. I have only tested on up-to-date raspbian and firmware.

    sudo rpi-update

Let me know how this update is working for you.
Claude ...
