### ISSUE TITLE
New makevideo.sh (replaces makemovie.sh and makedailymovie.sh)

### ISSUE THREAD

**Issue by pageauc** [pageauc/pi-timolo#39]
I have written a new makevideo.sh script that now replaces the makemovie.sh and makedailymovie.sh scripts.  I will leave the old files on the github repo for a while but local versions will be deleted as part of pi-timolo-install.sh.  To upgrade see easy install instructions here https://github.com/pageauc/pi-timolo

The new makevideo.sh script now handles moving encoded timelapse video to a remote share via a mount point.  An error message will indicate if there is no share mounted on the folder.  There is also a remove source files option.  This should be used with caution per code comments.
For additional info see the github wiki 
here https://github.com/pageauc/pi-timolo/wiki/How-to-Make-a-Timelapse-Video-from-Images
code here https://github.com/pageauc/pi-timolo/blob/master/source/makevideo.sh

**Comment by ozett** [comment]
i tried it today. looks promising 👍
