### ISSUE TITLE
Error when trying to run/setup grive

### ISSUE THREAD

**Issue by ghost** [pageauc/pi-timolo#4]
I am receiving this error in terminal:

./grive: error while loading shared libraries: libboost_filesystem.so.1.49.0: cannot open shared object file: No such file or directory

I think it must be some type of linking issue.  Any idea?

**Comment by pageauc** [comment]
Try installing this library.  Somehow it got missed but not sure how.  Let
me know if this solves your problem.

sudo apt-get install libboost1.49-dev

On Sun, Feb 8, 2015 at 7:57 PM, andrewmetersky notifications@github.com
wrote:

> I am receiving this error in terminal:
> 
> ./grive: error while loading shared libraries:
> libboost_filesystem.so.1.49.0: cannot open shared object file: No such file
> or directory
> 
> I think it must be some type of linking issue. Any idea?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pageauc/pi-timolo/issues/4.

## 

See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by ghost** [comment]
I'm still getting the same error.  Is there a specific place i need to install this?

**Comment by pageauc** [comment]
Libraries are installed per the installation apt-get scripts.  You may have
a corrupt system or an corrupt installation.

Do you get any errors during the setup.sh script?.
Are the grive, .py and .sh scripts executable?
Are you able to run sudo ./grive -a

If you still have problems you may want to try another RPI boot SD card
with the latest raspbian distro and repeat the installation per the
pi-timolo installation instructions and setup.sh script.

On Mon, Feb 9, 2015 at 8:07 PM, andrewmetersky notifications@github.com
wrote:

> I'm still getting the same error. Is there a specific place i need to
> install this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pageauc/pi-timolo/issues/4#issuecomment-73631384.

## 

See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by ghost** [comment]
I will try this! Thanks for your time.

**Comment by ghost** [comment]
So, I get not errors from the .sh or .py scripts, but grive is not executable.  I am looking in /usr/bin/ where all the lib files are and I do not see libboost_filesystem.so.1.49.0, but when i use sudo apt-get install libboost1.49-dev the output is:

Reading package lists... Done
Building dependency tree
Reading state information... Done
libboost1.49-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

**Comment by pageauc** [comment]
Until grive is fixed this item will remain closed.
