### ISSUE TITLE
tar file looks to be out of date

### ISSUE THREAD

**Issue by aggress** [pageauc/pi-timolo#7]
Hi, setup.sh in the tar file looks to be out of date, line 3 still has a typo in ehco

**Comment by pageauc** [comment]
Hi Richard

Thanks for the reminder.  I updated the repo with a new pi-timolo.tar that
contains the fixed setup-timolo.sh

Let me know if you find any other issues
Appreciate your notifying me.

On Mon, Jul 20, 2015 at 12:08 AM, Richard Shaw notifications@github.com
wrote:

> Hi, setup.sh in the tar file looks to be out of date, line 3 still has a
> typo in ehco
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pageauc/pi-timolo/issues/7.

## 

See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by aggress** [comment]
Many thanks Claude, this is an excellent project.
