### ISSUE TITLE
In makemovie.py the print statements are missing paranthesis

### ISSUE THREAD

**Issue by bradleycundari** [pageauc/pi-timolo#8]
I noticed today when I went to check over the makemovie.py script that all of the print statements are missing parenthesis which results in a syntax error. Is there a reason behind this that I'm missing?

**Comment by pageauc** [comment]
The original code was written for python 2.7.I updated pi-timolo.py to be
python 3 compliant but obviously missed makemovie.py.  I have updated the
pi-timolo repo files and tar file.  If you want to do a quick fix change to
the pi-timolo folder on the RPI and execute

2to3 -w makemovie.py

This will convert the file to be python3 compatible.  then delete the bak
file.

You can also download an updated tar file or the updated makemovie.py from
the github repo

Let me know if you have problems

Regards Claude ....

On Mon, Jul 20, 2015 at 12:15 PM, bradleycundari notifications@github.com
wrote:

> I noticed today when I went to check over the makemovie.py script that all
> of the print statements are missing parenthesis which results in a syntax
> error. Is there a reason behind this that I'm missing?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pageauc/pi-timolo/issues/8.

## 

See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by pageauc** [comment]
FYI

I have recently posted a python opencv motion tracking demo here
https://github.com/pageauc/motion-track
here is the YouTube demo video https://youtu.be/09JS7twPBsQ

Regards
Claude ...

On Mon, Jul 20, 2015 at 5:12 PM, Claude Pageau pageauc@gmail.com wrote:

> The original code was written for python 2.7.I updated pi-timolo.py to be
> python 3 compliant but obviously missed makemovie.py.  I have updated the
> pi-timolo repo files and tar file.  If you want to do a quick fix change to
> the pi-timolo folder on the RPI and execute
> 
> 2to3 -w makemovie.py
> 
> This will convert the file to be python3 compatible.  then delete the bak
> file.
> 
> You can also download an updated tar file or the updated makemovie.py from
> the github repo
> 
> Let me know if you have problems
> 
> Regards Claude ....
> 
> On Mon, Jul 20, 2015 at 12:15 PM, bradleycundari <notifications@github.com
> 
> > wrote:
> > 
> > I noticed today when I went to check over the makemovie.py script that
> > all of the print statements are missing parenthesis which results in a
> > syntax error. Is there a reason behind this that I'm missing?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/pageauc/pi-timolo/issues/8.
> 
> ## 
> 
> See my YouTube Channel at http://www.youtube.com/user/pageaucp

## 

See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by bradleycundari** [comment]
I had a feeling it might be because it was for 2.7. Slowly trying to immerse myself to help in projects, I'm new to GitHub. This is a very well written software package. Thanks Claude!

**Comment by pageauc** [comment]
New update to 2.8 released.  update gdrive and changed mencoder to avconv in makemovie scipts
